#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.4.5
# In conjunction with Tcl version 8.6
#    Jan 20, 2015 01:17:35 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import connection_screen_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('Pimped_Is_Loading')
    root.geometry('600x450+390+117')
    w = Pimped_Is_Loading (root)
    connection_screen_support.init(root, w)
    root.mainloop()

w = None
def create_Pimped_Is_Loading(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('Pimped_Is_Loading')
    w.geometry('600x450+390+117')
    w_win = Pimped_Is_Loading (w)
    connection_screen_support.init(w, w_win, param)
    return w_win

def destroy_Pimped_Is_Loading():
    global w
    w.destroy()
    w = None


class Pimped_Is_Loading:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 26 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#6c6c6c")


        self.lblLoading = Label(master)
        self.lblLoading.place(relx=0.38, rely=0.07, height=53, width=313)
        self.lblLoading.configure(background=_bgcolor)
        self.lblLoading.configure(disabledforeground="#a3a3a3")
        self.lblLoading.configure(font=font10)
        self.lblLoading.configure(foreground="#000000")
        self.lblLoading.configure(text='''PIMPED is loading...''')

        self.Text1 = Text(master)
        self.Text1.place(relx=0.38, rely=0.2, relheight=0.34, relwidth=0.34)
        self.Text1.configure(background=_bgcolor)
        self.Text1.configure(borderwidth="0")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="#000000")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=204)
        self.Text1.configure(wrap=WORD)

	def updateText(self, txt):
		self.lblLoading.configure(text=txt)




if __name__ == '__main__':
    vp_start_gui()



