#############################################################################
# Generated by PAGE version 4.4.5
# in conjunction with Tcl version 8.6
#    Jan 20, 2015 01:17:35 AM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#############################################################################
####################  vTcl:font:generate_font_use Starting
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 26 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
####################  vTcl:font:generate_font_use Ends
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#6c6c6c} 
    wm focusmodel $top passive
    wm geometry $top 600x450+390+117; update
    wm maxsize $top 1354 733
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Pimped Is Loading"
    vTcl:DefineAlias "$top" "tlvlLoadingLevel" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab39 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} -font font10 \
        -foreground {#000000} -text {PIMPED is loading...} 
    vTcl:DefineAlias "$top.lab39" "lblLoading" vTcl:WidgetProc "tlvlLoadingLevel" 1
    text $top.tex42 \
        -background {#d9d9d9} -borderwidth 0 -font TkTextFont \
        -foreground {#000000} -height 154 -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 204 \
        -wrap word 
    .top37.tex42 configure -font TkTextFont
    .top37.tex42 insert end text
    vTcl:DefineAlias "$top.tex42" "Text1" vTcl:WidgetProc "tlvlLoadingLevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab39 \
        -in $top -x 230 -y 30 -anchor nw -bordermode ignore 
    place $top.tex42 \
        -in $top -x 230 -y 90 -width 204 -height 154 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

