#############################################################################
# Generated by PAGE version 4.4.5
# in conjunction with Tcl version 8.6
#    Jan 16, 2015 06:00:43 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
#############################################################################
####################  vTcl:font:generate_font_use Starting
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Miriam Fixed} -size 36 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "font17" \
    user \
    vTcl:font27
####################  vTcl:font:generate_font_use Ends
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -menu "$top.m52" -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1264x692+3+66; update
    wm maxsize $top 1276 998
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Real time display"
    vTcl:DefineAlias "$top" "mainWindow" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font17 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 25MPH 
    vTcl:DefineAlias "$top.lab43" "lblSpeed" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font16 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text speed 
    vTcl:DefineAlias "$top.cpd50" "lblinfo1" vTcl:WidgetProc "mainWindow" 1
    menu $top.m52 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    label $top.cpd56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 234 
    vTcl:DefineAlias "$top.cpd56" "lblScrollerVal1" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text GPS: 
    vTcl:DefineAlias "$top.cpd58" "Label7" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font17 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 40MPG 
    vTcl:DefineAlias "$top.cpd59" "lblMPG" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font16 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text consumption 
    vTcl:DefineAlias "$top.cpd61" "lblinfo2" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Time: 
    vTcl:DefineAlias "$top.cpd62" "Label8" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {25N 34E} 
    vTcl:DefineAlias "$top.cpd63" "lblGPS" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {25min 32sec} 
    vTcl:DefineAlias "$top.cpd64" "lblTime" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font17 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 1000RPM 
    vTcl:DefineAlias "$top.cpd66" "lblRPM" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font16 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text revs 
    vTcl:DefineAlias "$top.cpd67" "lblinfo3" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Throttle 
    vTcl:DefineAlias "$top.cpd68" "lblScroller2" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Load 
    vTcl:DefineAlias "$top.cpd69" "lblScroller1" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 7 
    vTcl:DefineAlias "$top.cpd70" "lblScrollerVal2" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Miles 
    vTcl:DefineAlias "$top.cpd71" "lblMiles" vTcl:WidgetProc "mainWindow" 1
    label $top.cpd72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ffffff} -disabledforeground {#a3a3a3} -font font11 \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text 42 
    vTcl:DefineAlias "$top.cpd72" "lblMilesVal" vTcl:WidgetProc "mainWindow" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 230 -y 200 -anchor nw -bordermode ignore 
    place $top.cpd50 \
        -in $top -x 250 -y 290 -width 276 -height 33 -anchor nw \
        -bordermode inside 
    place $top.cpd56 \
        -in $top -x 10 -y 610 -width 406 -height 73 -anchor nw \
        -bordermode inside 
    place $top.cpd58 \
        -in $top -x 910 -y 20 -anchor nw -bordermode inside 
    place $top.cpd59 \
        -in $top -x 720 -y 200 -anchor nw -bordermode inside 
    place $top.cpd61 \
        -in $top -x 730 -y 290 -width 282 -height 33 -anchor nw \
        -bordermode inside 
    place $top.cpd62 \
        -in $top -x 30 -y 20 -anchor nw -bordermode inside 
    place $top.cpd63 \
        -in $top -x 1020 -y 20 -anchor nw -bordermode inside 
    place $top.cpd64 \
        -in $top -x 180 -y 20 -anchor nw -bordermode inside 
    place $top.cpd66 \
        -in $top -x 410 -y 370 -anchor nw -bordermode inside 
    place $top.cpd67 \
        -in $top -x 440 -y 460 -width 380 -height 33 -anchor nw \
        -bordermode inside 
    place $top.cpd68 \
        -in $top -x 850 -y 550 -width 406 -height 53 -anchor nw \
        -bordermode inside 
    place $top.cpd69 \
        -in $top -x 60 -y 550 -width 406 -height 53 -anchor nw \
        -bordermode inside 
    place $top.cpd70 \
        -in $top -x 850 -y 610 -width 406 -height 73 -anchor nw \
        -bordermode inside 
    place $top.cpd71 \
        -in $top -x 430 -y 550 -width 406 -height 53 -anchor nw \
        -bordermode inside 
    place $top.cpd72 \
        -in $top -x 430 -y 610 -width 406 -height 73 -anchor nw \
        -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

