#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.4.5
# In conjunction with Tcl version 8.6
#    Jan 16, 2015 06:41:20 PM
import sys
import threading 

from random import randint

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import realtimegui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('Real_time_display')
    root.geometry('1264x692+18+201')
    w = Real_time_display (root)
    realtimegui_support.init(root, w)
    root.mainloop()

w = None
def create_Real_time_display(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('Real_time_display')
    w.geometry('1264x692+18+201')
    w_win = Real_time_display (w)
    realtimegui_support.init(w, w_win, param)
    return w_win

def destroy_Real_time_display():
    global w
    w.destroy()
    w = None
    
class Real_time_display:
    
    def __init__(self, master=None):
        
        global temperatures
        
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family {Miriam Fixed} -size 48 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font16 = "-family {Miriam Fixed} -size 48 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font17 = "-family {Miriam Fixed} -size 120 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        master.configure(background="#ffffff")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.lblSpeed = Label(master)
        self.lblSpeed.place(relx=0.05, rely=0.17, height=140, width=520)
        self.lblSpeed.configure(activebackground="#f9f9f9")
        self.lblSpeed.configure(activeforeground="black")
        self.lblSpeed.configure(background="#ffffff")
        self.lblSpeed.configure(disabledforeground="#a3a3a3")
        self.lblSpeed.configure(font=font17)
        self.lblSpeed.configure(foreground="#000000")
        self.lblSpeed.configure(highlightbackground="#d9d9d9")
        self.lblSpeed.configure(highlightcolor="black")
        self.lblSpeed.configure(text='''25MPH''')

        self.lblinfo1 = Label(master)
        self.lblinfo1.place(relx=0.05, rely=0.35, height=55, width=520)
        self.lblinfo1.configure(activebackground="#f9f9f9")
        self.lblinfo1.configure(activeforeground="black")
        self.lblinfo1.configure(background="#ffffff")
        self.lblinfo1.configure(disabledforeground="#a3a3a3")
        self.lblinfo1.configure(font=font16)
        self.lblinfo1.configure(foreground="#000000")
        self.lblinfo1.configure(highlightbackground="#d9d9d9")
        self.lblinfo1.configure(highlightcolor="black")
        self.lblinfo1.configure(text='''speed''')

        self.menubar = Menu(master,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        
        self.lblNameTime = Label(master)
        self.lblNameTime.place(relx=0.02, rely=0.03, height=55, width=200)
        self.lblNameTime.configure(activebackground="#f9f9f9")
        self.lblNameTime.configure(activeforeground="black")
        self.lblNameTime.configure(background="#ffffff")
        self.lblNameTime.configure(disabledforeground="#a3a3a3")
        self.lblNameTime.configure(font=font11)
        self.lblNameTime.configure(foreground="#000000")
        self.lblNameTime.configure(highlightbackground="#d9d9d9")
        self.lblNameTime.configure(highlightcolor="black")
        self.lblNameTime.configure(text='''Time:''')

        self.lblTime = Label(master)
        self.lblTime.place(relx=0.17, rely=0.03, height=55, width=360)
        self.lblTime.configure(activebackground="#f9f9f9")
        self.lblTime.configure(activeforeground="black")
        self.lblTime.configure(background="#ffffff")
        self.lblTime.configure(disabledforeground="#a3a3a3")
        self.lblTime.configure(font=font11)
        self.lblTime.configure(foreground="#000000")
        self.lblTime.configure(highlightbackground="#d9d9d9")
        self.lblTime.configure(highlightcolor="black")
        self.lblTime.configure(text='''125m 32s''')

        self.lblNameGPS = Label(master)
        self.lblNameGPS.place(relx=0.60, rely=0.03, height=55, width=180)
        self.lblNameGPS.configure(activebackground="#f9f9f9")
        self.lblNameGPS.configure(activeforeground="black")
        self.lblNameGPS.configure(background="#ffffff")
        self.lblNameGPS.configure(disabledforeground="#a3a3a3")
        self.lblNameGPS.configure(font=font11)
        self.lblNameGPS.configure(foreground="#000000")
        self.lblNameGPS.configure(highlightbackground="#d9d9d9")
        self.lblNameGPS.configure(highlightcolor="black")
        self.lblNameGPS.configure(text='''GPS:''')
        
        self.lblGPS = Label(master)
        self.lblGPS.place(relx=0.73, rely=0.03, height=55, width=300)
        self.lblGPS.configure(activebackground="#f9f9f9")
        self.lblGPS.configure(activeforeground="black")
        self.lblGPS.configure(background="#ffffff")
        self.lblGPS.configure(disabledforeground="#a3a3a3")
        self.lblGPS.configure(font=font11)
        self.lblGPS.configure(foreground="#000000")
        self.lblGPS.configure(highlightbackground="#d9d9d9")
        self.lblGPS.configure(highlightcolor="black")
        self.lblGPS.configure(text='''25N 34E''')

        self.lblMPG = Label(master)
        self.lblMPG.place(relx=0.57, rely=0.17, height=140, width=520)
        self.lblMPG.configure(activebackground="#f9f9f9")
        self.lblMPG.configure(activeforeground="black")
        self.lblMPG.configure(background="#ffffff")
        self.lblMPG.configure(disabledforeground="#a3a3a3")
        self.lblMPG.configure(font=font17)
        self.lblMPG.configure(foreground="#000000")
        self.lblMPG.configure(highlightbackground="#d9d9d9")
        self.lblMPG.configure(highlightcolor="black")
        self.lblMPG.configure(text='''40MPG''')

        self.lblNameConsumption = Label(master)
        self.lblNameConsumption.place(relx=0.57, rely=0.35, height=55, width=520)
        self.lblNameConsumption.configure(activebackground="#f9f9f9")
        self.lblNameConsumption.configure(activeforeground="black")
        self.lblNameConsumption.configure(background="#ffffff")
        self.lblNameConsumption.configure(disabledforeground="#a3a3a3")
        self.lblNameConsumption.configure(font=font16)
        self.lblNameConsumption.configure(foreground="#000000")
        self.lblNameConsumption.configure(highlightbackground="#d9d9d9")
        self.lblNameConsumption.configure(highlightcolor="black")
        self.lblNameConsumption.configure(text='''consumption''')

        self.lblRPM = Label(master)
        self.lblRPM.place(relx=0.24, rely=0.45, height=140, width=680)
        self.lblRPM.configure(activebackground="#f9f9f9")
        self.lblRPM.configure(activeforeground="black")
        self.lblRPM.configure(background="#ffffff")
        self.lblRPM.configure(disabledforeground="#a3a3a3")
        self.lblRPM.configure(font=font17)
        self.lblRPM.configure(foreground="#000000")
        self.lblRPM.configure(highlightbackground="#d9d9d9")
        self.lblRPM.configure(highlightcolor="black")
        self.lblRPM.configure(text='''1000RPM''')

        self.lblNameRevs = Label(master)
        self.lblNameRevs.place(relx=0.35, rely=0.66, height=33, width=380)
        self.lblNameRevs.configure(activebackground="#f9f9f9")
        self.lblNameRevs.configure(activeforeground="black")
        self.lblNameRevs.configure(background="#ffffff")
        self.lblNameRevs.configure(disabledforeground="#a3a3a3")
        self.lblNameRevs.configure(font=font16)
        self.lblNameRevs.configure(foreground="#000000")
        self.lblNameRevs.configure(highlightbackground="#d9d9d9")
        self.lblNameRevs.configure(highlightcolor="black")
        self.lblNameRevs.configure(text='''revs''')

        self.lblScroller1 = Label(master)
        self.lblScroller1.place(relx=0.01, rely=0.79, height=53, width=406)
        self.lblScroller1.configure(activebackground="#f9f9f9")
        self.lblScroller1.configure(activeforeground="black")
        self.lblScroller1.configure(background="#ffffff")
        self.lblScroller1.configure(disabledforeground="#a3a3a3")
        self.lblScroller1.configure(font=font11)
        self.lblScroller1.configure(foreground="#000000")
        self.lblScroller1.configure(highlightbackground="#d9d9d9")
        self.lblScroller1.configure(highlightcolor="black")
        self.lblScroller1.configure(text='''Load''')
        
        self.lblScrollerVal1 = Label(master)
        self.lblScrollerVal1.place(relx=0.01, rely=0.88, height=73, width=406)
        self.lblScrollerVal1.configure(activebackground="#f9f9f9")
        self.lblScrollerVal1.configure(activeforeground="black")
        self.lblScrollerVal1.configure(background="#ffffff")
        self.lblScrollerVal1.configure(disabledforeground="#a3a3a3")
        self.lblScrollerVal1.configure(font=font11)
        self.lblScrollerVal1.configure(foreground="#000000")
        self.lblScrollerVal1.configure(highlightbackground="#d9d9d9")
        self.lblScrollerVal1.configure(highlightcolor="black")
        self.lblScrollerVal1.configure(text='''234''')
        
        self.lblMiles = Label(master)
        self.lblMiles.place(relx=0.34, rely=0.79, height=53, width=406)
        self.lblMiles.configure(activebackground="#f9f9f9")
        self.lblMiles.configure(activeforeground="black")
        self.lblMiles.configure(background="#ffffff")
        self.lblMiles.configure(disabledforeground="#a3a3a3")
        self.lblMiles.configure(font=font11)
        self.lblMiles.configure(foreground="#000000")
        self.lblMiles.configure(highlightbackground="#d9d9d9")
        self.lblMiles.configure(highlightcolor="black")
        self.lblMiles.configure(text='''Miles''')

        self.lblMilesVal = Label(master)
        self.lblMilesVal.place(relx=0.34, rely=0.88, height=73, width=406)
        self.lblMilesVal.configure(activebackground="#f9f9f9")
        self.lblMilesVal.configure(activeforeground="black")
        self.lblMilesVal.configure(background="#ffffff")
        self.lblMilesVal.configure(disabledforeground="#a3a3a3")
        self.lblMilesVal.configure(font=font11)
        self.lblMilesVal.configure(foreground="#000000")
        self.lblMilesVal.configure(highlightbackground="#d9d9d9")
        self.lblMilesVal.configure(highlightcolor="black")
        self.lblMilesVal.configure(text='''42''')
        
        self.lblScroller2 = Label(master)
        self.lblScroller2.place(relx=0.67, rely=0.79, height=53, width=406)
        self.lblScroller2.configure(activebackground="#f9f9f9")
        self.lblScroller2.configure(activeforeground="black")
        self.lblScroller2.configure(background="#ffffff")
        self.lblScroller2.configure(disabledforeground="#a3a3a3")
        self.lblScroller2.configure(font=font11)
        self.lblScroller2.configure(foreground="#000000")
        self.lblScroller2.configure(highlightbackground="#d9d9d9")
        self.lblScroller2.configure(highlightcolor="black")
        self.lblScroller2.configure(text='''Throttle''')

        self.lblScrollerVal2 = Label(master)
        self.lblScrollerVal2.place(relx=0.67, rely=0.88, height=73, width=406)
        self.lblScrollerVal2.configure(activebackground="#f9f9f9")
        self.lblScrollerVal2.configure(activeforeground="black")
        self.lblScrollerVal2.configure(background="#ffffff")
        self.lblScrollerVal2.configure(disabledforeground="#a3a3a3")
        self.lblScrollerVal2.configure(font=font11)
        self.lblScrollerVal2.configure(foreground="#000000")
        self.lblScrollerVal2.configure(highlightbackground="#d9d9d9")
        self.lblScrollerVal2.configure(highlightcolor="black")
        self.lblScrollerVal2.configure(text='''7''')

        temperatures = False 
        self.startTimer(5.0)
        
    def switchLabels(self):
        global temperatures
        if(temperatures):
            self.lblScroller1.configure(text='''Engine''')
            self.lblScrollerVal1.configure(text='''137oC''')
            self.lblScroller2.configure(text='''Air''')
            self.lblScrollerVal2.configure(text='''7oC''')
            temperatures = False

        else:
            self.lblScroller1.configure(text='''Load''')
            self.lblScrollerVal1.configure(text='''200''')
            self.lblScroller2.configure(text='''Throttle''')
            self.lblScrollerVal2.configure(text='''30''')
            temperatures = True
            
        self.startTimer(5.0)
        
    def startTimer(self, time):
        
            threading.Timer(time, self.switchLabels).start()
        
if __name__ == '__main__':
    vp_start_gui()



